DROP TABLE IF EXISTS PLANT_USE;
DROP TABLE IF EXISTS PLANT;
DROP TABLE IF EXISTS USE;


CREATE TABLE PLANT(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CREATION_DATE DATE NOT NULL,
  PHOTO LONGBLOB,
  PRIMARY KEY (ID)
);

CREATE TABLE USE(
    ID INT NOT NULL  AUTO_INCREMENT,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR2(250),
    PRIMARY KEY (ID)
);

CREATE TABLE PLANT_USE(
  PLANT_ID INT NOT NULL,
  USE_ID INT NOT NULL,
  PRIMARY KEY (PLANT_ID, USE_ID),
  CONSTRAINT FK_PLANT_ID_1 FOREIGN KEY (PLANT_ID) REFERENCES PLANT(ID) ON DELETE CASCADE,
  CONSTRAINT FK_USE_ID_1 FOREIGN KEY (USE_ID) REFERENCES USE(ID)
);
